// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUPnEKpcVpEZyF17WLqR6RA6xEUX9VVHo',
    appId: '1:1087981444280:web:6a6e8da6ec822ac7ee284d',
    messagingSenderId: '1087981444280',
    projectId: 'remainder-12352',
    authDomain: 'remainder-12352.firebaseapp.com',
    storageBucket: 'remainder-12352.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppqytLd9gZ_qLx1P_Rxttar_quXHZf28',
    appId: '1:1087981444280:android:12b5e655df3e88c9ee284d',
    messagingSenderId: '1087981444280',
    projectId: 'remainder-12352',
    storageBucket: 'remainder-12352.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeqJR_Atb_RJAYc6cSYjGStdTgOYqz0r0',
    appId: '1:1087981444280:ios:515705bcb91b7d65ee284d',
    messagingSenderId: '1087981444280',
    projectId: 'remainder-12352',
    storageBucket: 'remainder-12352.appspot.com',
    androidClientId: '1087981444280-nc3l94kbqafe0gv87gvo83rds2a084s2.apps.googleusercontent.com',
    iosClientId: '1087981444280-jbiolftuqqbd3giiamrajcd0nnthlrqr.apps.googleusercontent.com',
    iosBundleId: 'com.boringtimes.copier.copier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeqJR_Atb_RJAYc6cSYjGStdTgOYqz0r0',
    appId: '1:1087981444280:ios:92c7e45a08b9114eee284d',
    messagingSenderId: '1087981444280',
    projectId: 'remainder-12352',
    storageBucket: 'remainder-12352.appspot.com',
    androidClientId: '1087981444280-nc3l94kbqafe0gv87gvo83rds2a084s2.apps.googleusercontent.com',
    iosClientId: '1087981444280-v9o6dche2g0d5qs7k7k89d2stcjdj4fk.apps.googleusercontent.com',
    iosBundleId: 'com.boringtimes.copier.copier.RunnerTests',
  );
}
